### ISSUE TITLE
/rp flag case error

### ISSUE THREAD

**Issue by jaciloy** [FabioZumbi12/Sponge-RedProtect-18#15]
`[08:23:07] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'rp flag' for source EntityPlayerMP['rata'/905, l='world', x=-401.02, y=86.85, z=-625.78]: Could not find a Supplier for the provided class: org.spongepowered.api.item.inventory.custom.CustomInventory.Builder
java.lang.IllegalArgumentException: Could not find a Supplier for the provided class: org.spongepowered.api.item.inventory.custom.CustomInventory.Builder
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.9.jar:?]
	at org.spongepowered.common.registry.SpongeGameRegistry.createBuilder(SpongeGameRegistry.java:264) ~[SpongeGameRegistry.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.api.item.inventory.custom.CustomInventory.builder(CustomInventory.java:45) ~[CustomInventory.class:1.8.9-1890-4.1.0-BETA-1395]
	at br.net.fabiozumbi12.redprotect.RPGui.<init>(RPGui.java:111) ~[RPGui.class:?]
	at br.net.fabiozumbi12.redprotect.listeners.RPCommands.process(RPCommands.java:647) ~[RPCommands.class:?]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:269) [SpongeCommandManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:115) [PacketUtil.class:1.8.9-1890-4.1.0-BETA-1395]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by FabioZumbi12** [comment]
Waiting API implementation for custom inventory. Already removed until not implemented.
